# Fetching the minified node image on apline linux
FROM node:20

# Declaring env
ENV NODE_ENV development

RUN npm install -g bun

# Setting up the work directory
WORKDIR /app

# Copying all the files in our project
COPY package.json ./
COPY bun.lockb ./
# Installing dependencies
RUN bun install

COPY . .
COPY prisma ./prisma

RUN bunx prisma generate

# Starting our application
CMD [ "bun", "run", "dev" ]