services:
  db:
    image: 'postgres:16'
    restart: 'always'
    container_name: 'db'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'blimresearch-dev'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
