# Fetching the minified node image on apline linux
FROM node:20
# Declaring env
ENV NODE_ENV development

RUN apt-get update && apt-get install -y ffmpeg

# Setting up the work directory
WORKDIR /app

# Copying all the files in our project
COPY package*.json ./
# Installing dependencies
RUN npm install

COPY . .
COPY prisma ./prisma

RUN npx prisma generate

# Starting our application
CMD [ "npm", "run", "dev" ]