# Fetching the minified node image on apline linux
FROM oven/bun:slim

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /app

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN bun install

COPY prisma ./prisma

RUN bunx prisma generate

# Starting our application
CMD [ "bun", "run", "--watch" ,"./src/index.ts" ]

# Exposing server port
EXPOSE 5000